WARNING! DEAD CODE!

(define MAXLETTERS 16)
(define HEIGHT 42)
(define WIDTH 11)

(local
	arrayBuilt = 		FALSE
	cur = 				0
	tempIndx	 =			0
	mainArray =   		0	
	aStrLen 	 =		   0
	InitCmpArr = 		[`a `b `c `d `e `f `g `h `k `m `n `p `s `v `w `y]
	wordCountArr = 	[ 2  2  4  2  1 14  1  1  2  2  1  3  4  1  1  2]
	profaneArray =		[ 	"asswipe*"  ;; entry 0
								"asshole*"
								"bitch***"
								"blowjob*"
								"cock****"
								"cunt****"
								"clit****"
								"chink*"
								"dickhead*"
								"dickwad*"
								"eatshit*"
								"fag*****"
								"faggot**"
								"fuck****"
								"fucking*"
								"fvck****"
								"fvcking*"
								"fucked*"
								"fuckedup*"
								"fucku*"
								"fuckyou*"
								"fuckface*"
								"fuckhead*"
								"fucker*"
								"fuckme*"
								"gook****"
								"homo****"
								"kunt****"
								"klit****"
								"mydick**"
								"myass***"
								"nigger**"
								"penis***"
								"pussy***"
								"phuck***"
								"schlong*"
								"slut****"
								"shit****"
								"sphincter*"
								"vagina*"
								"whore***"
								"yourass*"
								"yourdick*" ;; entry 42
							]	 
)








