;asswipe*
;asshole*
;ashole**
;asshol**
;ashol***
;bitch***
;bich****
;bch*****
;blwjob**
;blwjb***
;blowjob*
;bastard*
;cock****
;cok*****
;cunt****
;cnt*****
;clit****
;chink***
;damn****
;dickhead*
;dickhed*
;dikhead*
;dichead*
;dikhed**
;fag*****
;faggot**
;fuck****
;fuk*****
;fuc*****
;fvck****
;fvk*****
;fvc*****
;gook****
;homo****
;honky***
;honki***
;hore****
;hisdick*
;hisdik**
;hisass**
;herass**
;koc*****
;kok*****
;kunt****
;knt*****
;klit****
;knocker*
;mydik***
;mydic***
;mydick**
;myass***
;myazz***
;nigger**
;penis***
;pussy***
;pusy****
;phuck***
;phuc****
;phuk****
;prick***
;pric****
;prik****
;schlong*
;shlong**
;slut****
;shit****
;titty***
;titties*
;tities**
;whore***
;yourass*
;yourdick*
;yourdik*
;yourdic*









