;; Please refer to lists.sc for more information about this file.
;;
(define 	InitGlobalLists 	(ModuleID LISTS 0))
(define 	GEffectList 	 	(ModuleID LISTS 1))
(define 	GMovieCmdList 	 	(ModuleID LISTS 2))
(define 	GBaseList 		 	(ModuleID LISTS 3))
(define	GATPList			 	(ModuleID LISTS 4))
(define	GPicInfoList	 	(ModuleID LISTS 5))
(define	GSpellList			(ModuleID LISTS 6))
(define	GSEList				(ModuleID LISTS 7))
(define	GlobalStockObjList	(ModuleID STOCKOBJ0 0))
