//
// msgfunctions
//
// This file contains network messaging functions.
//
// author: Stephen Nichols
//

/*
SYNC - server - msgs.hpp 
	 - client - netmsg.sh
	 - client - msgfunctions.hpp
*/


#ifndef _MSGFUNCTIONS_HPP_
#define _MSGFUNCTIONS_HPP_

#include "C++SCI.hpp"
#include "packdataC.hpp"

// enumerate the NAK error codes
enum ServerReturnCodes {
	_ERR_INTERNAL				=	10000,
	_ERR_REDUNDANT,
	_ERR_NO_ROOM,
	_ERR_MUST_REMOVE,
	_ERR_BAD_SERVID,
	_ERR_BAD_ROOM,
	_ERR_SERVICE_NOT_AVAILABLE,
	_ERR_MUST_UNLOCK,
	_ERR_WRONG_KEY,
	_ERR_MUST_OPEN,
	_ERR_WONT_FIT,
	_ERR_CANT_WEAR,
	_ERR_TOO_BULKY,
	_ERR_TOO_HEAVY,
	_ERR_TOO_EXPENSIVE,
	_ERR_DEAD,
	_ERR_ACCESS_LOCKED,
	_ERR_BAD_PASSWORD,
	_ERR_FROZEN,
	_ERR_NONSENSE,
	_ERR_NOT_MAGICAL,
	_ERR_TOO_FAR,
	_ERR_NO_SHIELD,
	_ERR_NO_WEAPON,
	_ERR_BAD_PACKAGE,
	_ERR_TOO_TIRED,
	_ERR_STRENGTH_FAILURE,
	_ERR_DEXTERITY_FAILURE,
	_ERR_INTELLIGENCE_FAILURE,
	_ERR_QUICKNESS_FAILURE,
	_ERR_ENDURANCE_FAILURE,
	_ERR_MEMORIZE_FAILURE,
	_ERR_SKILL_FAILURE,
	_ERR_TOO_VAGUE,
	_ERR_BAD_OBJECT,
	_ERR_CANT_APPROACH			=	50000,
	_ERR_SEATED,
};

enum ServerValues {
	REALM_PATCH_REQUEST	=	6,
	REALM_PATCH_BLOCK,
	REALM_PATCH_INFO,

	REALM_CHECK_LOGIN =		14,
	REALM_SECURITY,
	REALM_GATE_LOGIN,
	REALM_SERVER_PING,
	REALM_QUERY_CHARACTERS,			//	50

	REALM_OLD_GATE_LOGIN	=	20,
	REALM_PLAYER_LOGIN,
	REALM_LOGOUT,
	REALM_PAGE,
	REALM_SYSTEM_MSG,
	REALM_ACK,
	REALM_NAK,
	REALM_ADD_ROOM,
	REALM_READ_ROOM,
	REALM_UPDATE_ROOM,
	REALM_DELETE_ROOM,
	REALM_UNLINK_ROOM,
	REALM_CHANGE_ROOM,
	REALM_NEW_ROOM,
	REALM_INVALIDATE_ROOMS,
	REALM_ENTERED_ROOM,
	REALM_EXITED_ROOM,
	REALM_ROOM_CHAT,
	REALM_TEXT,
	REALM_CREATE_OBJ,
	REALM_OBJ_INFO,
	REALM_MOVIE,
	REALM_MOVIE_DATA,
	REALM_CHAT,
	REALM_SERVID,
	REALM_DESTROY_OBJECT,
	REALM_OLD_SERVER_PING,
	REALM_CLIENT_PING,
	REALM_CREATE_CHARACTER,
	REALM_DESTROY_CHARACTER,
	REALM_OLD_QUERY_CHARACTERS,			//	50
	REALM_REQUEST_SERVID,
	REALM_SHIFT_ROOM,
	REALM_CHARACTER_INFO,
	REALM_OLD_CHARACTER_LOGIN,
	REALM_GET_BIOGRAPHY,
	REALM_SET_BIOGRAPHY,
	REALM_GET_DESCRIPTION,
	REALM_GET_EXTENDED_PROPS,
	REALM_SET_HEAD_DATA,
	REALM_GET_CHAR_INFO,
	REALM_WHO,
	REALM_OLD_CHECK_LOGIN,
	REALM_ATTACH_EFFECT,
	REALM_REMOVE_EFFECT,
	REALM_EFFECT_DATA,
	REALM_SET_PROP,
	REALM_COMBAT_BEGIN,
	REALM_COMBAT_MOVE,
	REALM_COMBAT_EXIT,
	REALM_COMBAT_FLEE,
	REALM_GET_SHOP_INFO,
	REALM_BUY_ITEM,
	REALM_EXAMINE_ITEM,
	REALM_SELL_ITEM,
	REALM_GET_PRICE,
	REALM_MONEY_DROP,
	REALM_MONEY_PUT,
	REALM_MONEY_GIVE,
	REALM_MONEY_TAKE,
	REALM_CAST_SPELL,
	REALM_INFO,
	REALM_GET_BOOK_INFO,
	REALM_GET_BOOK_PAGE,
	REALM_FATAL_DATA,
	REALM_LOCK_OBJ,
	REALM_UNLOCK_OBJ,
	REALM_JOIN_GROUP,
	REALM_LEAVE_GROUP,
	REALM_KICK_GROUP,
	REALM_QUESTION_GROUP,
	REALM_SECURITY_REQUEST,
	REALM_GET_POSN,
	REALM_CHANGE_PASSWORD,
	REALM_GET_HOUSE,
	REALM_ENTRY_INFO,
	REALM_TALK,
	REALM_LOGIN_DONE,
	REALM_LOGIN_UPDATE,
	REALM_FOREFIT_TURN,
	REALM_GET_ROUTE,
	REALM_RECHARGE,
	REALM_GET_RECHARGE_PRICE,
	REALM_SET_TITLE,
	REALM_TREE_GET,
	REALM_TREE_CHOOSE_TOPIC,
	REALM_TREE_GET_TEXT,
	REALM_TREE_BACK,
	REALM_QUEST_ACCEPT,
	REALM_QUEST_DECLINE,
	REALM_GET_QUEST_LIST,
	REALM_MIX_OBJECT,
	REALM_COMBAT_ACTION,
	REALM_CREATE_OBJECT,
	REALM_WHATS_NEW,
	REALM_SET_ENGRAVE_NAME,
	REALM_LOOK_INFO,
	REALM_SELL_CRYSTALS,
	REALM_BULK_TAKE,
	REALM_BULK_DROP,
	REALM_BULK_PUT,
	REALM_BULK_GIVE,
	REALM_REPAIR,
	REALM_GET_REPAIR_PRICE,
	REALM_UPDATE_CHARACTER,
    REALM_SEND_REG,
	REALM_MASS_SELL,
	REALM_MASS_BUY,
	REALM_GET_SELL_PRICES,
	REALM_CREATE_CHANNEL,
	REALM_CHARACTER_LOGIN,
	REALM_GET_REPAIR_PRICES,
	REALM_MASS_REPAIR,
	REALM_ROCKING,

	REALM_TRADE,

	REALM_MAIL_LIST_GET =	135,
	REALM_MAIL_MESSAGE_GET,
	REALM_MAIL_MESSAGE_DELETE,
	REALM_MAIL_MESSAGE_SEND,
	REALM_MAIL_MESSAGE_ARCHIVE,
	REALM_MAIL_MESSAGE_COMPLAIN,

	REALM_WRITE_SPELLS	=	145,

	REALM_VERB_TAKE	=	150,
	REALM_VERB_DROP,
	REALM_VERB_PUT_IN,
	REALM_VERB_PUT_ON,
	REALM_VERB_TAKE_OFF,
	REALM_VERB_OPEN,
	REALM_VERB_CLOSE,
	REALM_VERB_LOCK,
	REALM_VERB_UNLOCK,
	REALM_VERB_ATTACK,
	REALM_VERB_START_COMBAT,
	REALM_VERB_CONSUME,
	REALM_VERB_SIT,
	REALM_VERB_STAND,
	REALM_VERB_GIVE,
	REALM_VERB_MEMORIZE,
	REALM_VERB_ROB,
	REALM_VERB_USE,
	REALM_VERB_PUSH,
	REALM_VERB_DYE,

	REALM_HACKER =		254,
};

enum TradeFunction
{
	TRADE_START, //not used from interp
	TRADE_QUESTION,
	TRADE_OPEN,
	TRADE_CLOSE,
	TRADE_CHECK_ON,
	TRADE_CHECK_OFF,
	TRADE_OBJ_LOOK,
	TRADE_OBJ_ADD,
	TRADE_OBJ_LIST
};


// send a chat message to the server...
void MsgSendChat ( char *pFormat, ... );
void MsgSendWhatsNew ();
void MsgSendBuy ( CSCI_WorldObject hObject, int nConjureId );
void MsgSendMassBuy ( CSCI_WorldObject hObject, CPackedData* pData );
void MsgSendMassSell ( CPackedData* pData );
void MsgSendMassRepair ( CPackedData* pData );
void MsgSendBuyCrystals ( CSCI_WorldObject hObject, int nConjureId, int nQuantity );
void MsgExamineBuyItem ( CSCI_WorldObject hObject, int nConjureId );
void MsgSendCreateChannel( int nChannel, const char* sTitle, const char* sTopic, const char* sPassword );

#endif